Import of SBECK/Shell-Cmd-2.00 from CPAN.
gitpan-cpan-distribution: Shell-Cmd
gitpan-cpan-version:      2.00
gitpan-cpan-path:         SBECK/Shell-Cmd-2.00.tar.gz
gitpan-cpan-author:       SBECK
gitpan-cpan-maturity:     released

diff --git a/t/bin/fail b/t/bin/fail
--- a/t/bin/fail
+++ b/t/bin/fail
@@ -1,5 +1,7 @@
-#!/bin/sh
+#!/usr/bin/perl
+$| = 1;
 
-echo "This will fail"
-echo "It will give an error" >&2
-exit 1
+print "This is the 'fail' command\n";
+warn  "It will give an error\n";
+print "It will fail\n";
+exit 10;
diff --git a/t/bin/fail_twice b/t/bin/fail_twice
--- a/t/bin/fail_twice
+++ b/t/bin/fail_twice
@@ -1,19 +1,22 @@
-#!/bin/sh
+#!/usr/bin/perl
+$| = 1;
 
-if [ ! -f "touch_1" ]; then
-   echo "Running first time"
-   echo > touch_1
-   echo "Failing first time" >&2
-   exit 1
-fi
+if ( ! -f "fail_twice_1" ) {
+   print "Running first time\n";
+   open(OUT, ">fail_twice_1");
+   close(OUT);
+   warn  "Failing first time\n";
+   exit 20;
+}
 
-if [ ! -f "touch_2" ]; then
-   echo "Running second time"
-   echo > touch_2
-   echo "Failing second time" >&2
-   exit 1
-fi
+if ( ! -f "fail_twice_2" ) {
+   print "Running second time\n";
+   open(OUT, ">fail_twice_2");
+   close(OUT);
+   warn "Failing second time\n";
+   exit 21;
+}
 
-echo "Running third time"
-rm touch_1 touch_2
-exit 0
+print "Running third time\n";
+unlink ("fail_twice_1","fail_twice_2");
+exit 0;
